specVersion: 0.2.0
name: parami-scaner
version: 1.0.0
description: >-
  parami: parallel metaverse identity; and AD platform on web3, for KOL and
  creator.
repository: https://github.com/parami-protocol/parami-scaner
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xc4a827d5069aae4fa60f8560f8360c936f6d9c442ce068b59d70ed81aee5c311'
  endpoint: wss://rpc.parami.io/ws
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleDidAssigned
          kind: substrate/EventHandler
          filter:
            module: did
            method: Assigned
        - handler: handleNftMinted
          kind: substrate/EventHandler
          filter: 
            module: nft
            method: Minted
        - handler: handleAdPayout
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Paid
        - handler: handleAd3Transaction
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAdvertisementCreate
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Deposited
        - handler: handleAdvertisementBid
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Bid
        - handler: handleSlotRemainChanged
          kind: substrate/EventHandler
          filter:
            module: ad
            method: SwapTriggered
        - handler: handleAssetTransferred
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleAssetBurned
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Burned