specVersion: 0.2.0
name: parami-scaner
version: 1.0.0
description: >-
  parami: parallel metaverse identity; and AD platform on web3, for KOL and
  creator.
repository: https://github.com/parami-protocol/parami-scaner
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x2771615a4f7164aab679fe9d2e8988e119abef2c2df8f456f6ebc76a63298772"
  endpoint: wss://rpc.parami.io/ws
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleDidAssigned
          kind: substrate/EventHandler
          filter:
            module: did
            method: Assigned
        - handler: handleDidTransferred
          kind: substrate/EventHandler
          filter: 
            module: did
            method: Transferred
        - handler: handleAdPayout
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Paid
        - handler: handleAd3Transaction
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAdvertisementCreate
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Deposited
        - handler: handleAdvertisementBid
          kind: substrate/EventHandler
          filter:
            module: ad
            method: Bid
        - handler: handleSlotRemainChanged
          kind: substrate/EventHandler
          filter:
            module: ad
            method: SwapTriggered
        - handler: handleAssetTransferred
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleAssetBurned
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Burned
        - handler: handleTokenBought
          kind: substrate/EventHandler
          filter:
            module: swap
            method: TokenBought
        - handler: handleTokenSold
          kind: substrate/EventHandler
          filter:
            module: swap
            method: TokenSold
        - handler: handleNftCreated
          kind: substrate/EventHandler
          filter:
            module: nft
            method: Created
        - handler: handleNftMinted
          kind: substrate/EventHandler
          filter:
            module: nft
            method: Minted